version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3308'
    env_file:
      - .env
